### ISSUE TITLE
Can't login to Nano as of today

### ISSUE THREAD

**Issue by aarsan** [mwrock/packer-templates#17] opened 2015-11-12 01:10 UTC
This is odd. Today, I updated Virtualbox to the latest version and I can no longer use vagrant / vagrant to log into Windows Nano Server. It tells me I have incorrect credentials. I realize that it is unlikely that the version of Virtualbox has anything to do with it but that is all that has changed, from what I can tell. I tried deleting / re-downloading the box but I get the same error. Any ideas?

**Comment by mwrock** [comment] 2015-11-12 04:36
Ahhh man. I'm betting this is an expired password. Same is happening on my Hyper-V box. Typically when using packer I sysprep as the last step and thus the password expiration timer starts ticking after the first vagrant up. Nano has no sysprep so the timer started when the packer template created the original box file. This is usually not an issue since I use vagrant boxes "ephemerally" but a best practice regardless would be t oedit the user and set the password to never expire. I'm going to edit the scripts to do that and cut a new box.

**Comment by mwrock** [comment] 2015-11-12 05:25
Yup. Confirmed. There is still an active "administrator" account with password "vagrant" so I:
```
Enter-PSSession -Computername <my nano IP> -Credential administrator
```
Then ran
```
wmic useraccount where "name='vagrant'" set PasswordExpires=FALSE
```
And then the vagrant user worked. I'll close this after publishing a new box.

**Closed** 2015-11-12 16:37 UTC

**Comment by mwrock** [comment] 2015-11-12 16:39
Update to 0.1.1 fixes this

**Comment by aarsan** [comment] 2015-11-12 16:42
Thanks!!
